### ISSUE TITLE
How Can I Set the Default to My Text Editor

### ISSUE THREAD

**Issue by amarz45** [green7ea/sesame#2]
When a file I want to open with sesame does not have an extension or mime type, it is usually a shell script and I want to open it with my text editor. This happens when I try to run `sesame file`:

```
file (ext: file, proto: -, mime: -)
```

**Comment by green7ea** [comment]
The way the evaluation works is that every entry in the main list is evaluated and the first one that passes is used to launch the file. If there is a simple string, this will always be used to open any file that makes it there so usually this should go at the end.

For example, this configuration would fall back to `emacs` if the file doesn't have the `pdf` extension or the `video` mime type.

```
[
  {
    "extension": {
      "pdf": "zathura",
    }
  },

  {
    "mime": {
      "video": "mpv",
    }
  },

  "emacs"
]
```

This works because I'm using the graphical `emacs` editor. If I wanted to launch an editor through a new instance of a terminal, that doesn't yet work. It would have to support a syntax like `["kitty", "vim"]` but doesn't yet.

I hope this solves your use case. I will add support for launching terminal programs soonish in case you prefer a terminal editor.

**Comment by green7ea** [comment]
The latest version should allow you to specify `["kitty", "vim"]` to open vim inside a terminal (kitty) as well.

Let me know if this resolves your use case ;-).

**Comment by amarz45** [comment]
Yep, it resolved my issue. I just added `["alacritty", "-e", "vi"]` and it works.

**Comment by green7ea** [comment]
Small syntax change, it should now be:

```
"alacritty -e vi"
```

Which is easier to type and read than the array format.
